export default actionTypes = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCEED : "LOGIN_REQUEST_SUCCEED",

    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_REQUEST_SUCCEED : "SIGNUP_REQUEST_SUCCEED",

    AUTH_ERROR : "AUTH_ERROR",

    UPDATE_USER : "UPDATE_USER",

    SET_ERROR_FALSE: "SET_ERROR_FALSE",

    CHEK_USER: "CHEK_USER",
    IS_USER_FOUND: "IS_USER_FOUND",
    IS_USER_FOUND_FAIL: "IS_USER_FOUND_FAIL",
    

    LOAD_ALL_TABLES: "LOAD_ALL_TABLES",
    LOAD_ALL_TABLES_SUCCESS: "LOAD_ALL_TABLES_SUCCESS",
    LOAD_ALL_TABLES_ERROR: "LOAD_ALL_TABLES_ERROR",
    LOAD_ALL_TABLES_ERROR_TRUE:"LOAD_ALL_TABLES_ERROR_TRUE",

    LOAD_MENU_PROGRESS:'LOAD_MENU_PROGRESS',
    LOAD_MENU_SUCCESS : 'LOAD_MENU_SUCCESS',
    LOAD_MENU_ERROR:'LOAD_MENU_ERROR',

    PUSH_ORDER_PROGRESS: 'PUSH_ORDER_PROGRESS',
    PUSH_ORDER_SUCCESS:'PUSH_ORDER_SUCCESS',
    PUSH_ORDER_ERROR:'PUSH_ORDER_ERROR',
    

    SET_TABLE_ID : 'SET_TABLE_ID',
    SET_ORDER_ID : 'SET_ORDER_ID',

    SET_UPDATE_FLAG : 'SET_UPDATE_FLAG',

    UPDATE_ORDER_REQUEST: 'UPDATE_ORDER_REQUEST',
    UPDATE_ORDER_SUCCESS: 'UPDATE_ORDER_SUCCESS',
    UPDATE_ORDER_ERROR: 'UPDATE_ORDER_ERROR'

}