export default actionTypes = {
    LOGIN_REQUEST = "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCEED = "LOGIN_REQUEST_SUCCEED",

    SIGNUP_REQUEST = "SIGNUP_REQUEST",
    SIGNUP_REQUEST_SUCCEED = "SIGNUP_REQUEST_SUCCEED",

    AUTH_ERROR = "AUTH_ERROR",

    UPDATE_USER = "UPDATE_USER",
}