export default actionTypes = {
    LOGIN_REQUEST : "LOGIN_REQUEST",
    LOGIN_REQUEST_SUCCEED : "LOGIN_REQUEST_SUCCEED",

    SIGNUP_REQUEST : "SIGNUP_REQUEST",
    SIGNUP_REQUEST_SUCCEED : "SIGNUP_REQUEST_SUCCEED",

    AUTH_ERROR : "AUTH_ERROR",

    UPDATE_USER : "UPDATE_USER",

    SET_ERROR_FALSE: "SET_ERROR_FALSE",

    CHEK_USER: "CHEK_USER",

    IS_USER_FOUND: "IS_USER_FOUND",

    LOAD_ALL_TABLES: "LOAD_ALL_TABLES",
    LOAD_ALL_TABLES_SUCCESS: "LOAD_ALL_TABLES_SUCCESS",
    LOAD_ALL_TABLES_ERROR: "LOAD_ALL_TABLES_ERROR",
    LOAD_ALL_TABLES_ERROR_TRUE:"LOAD_ALL_TABLES_ERROR_TRUE",

}